#!/usr/bin/env bash

# regex to validate in commit msg
commit_regex='\[[0-1]+\]\s{1}\w+'
error_msg="Aborting commit. Valid Regex: $commit_regex"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi